#import "@/queries/component-blocks/header.gql"
#import "@/queries/component-blocks/footer.gql"
#import "@/queries/component-blocks/main-hero.gql"
#import "@/queries/component-blocks/simple-block.gql"
#import "@/queries/page-templates/page-seo.gql"

query QUERY_PAGE_BY_SLUG($slug: String!, $isPreview: Boolean!) {
  componentPageCollection(
    where: { pageSlug: $slug }
    limit: 1
    preview: $isPreview
  ) {
    items {
      pageName
      pageSlug
      pageSeo {
        ...PageSeoFragment
      }
      pageContentsCollection {
        items {
          ... on ComponentHeader {
            ...HeaderFragment
          }
          ... on ComponentFooter {
            ...FooterFragment
          }
          ... on ComponentMainHero {
            ...MainHeroFragment
          }
          ... on ComponentSimpleBlock {
            ...SimpleBlockFragment
          }
        }
      }
    }
  }
}
