#import "@/queries/component-blocks/header.gql"
#import "@/queries/component-blocks/footer.gql"
#import "@/queries/component-blocks/main-hero.gql"
#import "@/queries/component-blocks/attire-block.gql"
#import "@/queries/component-blocks/simple-block.gql"
#import "@/queries/component-blocks/timeline-block.gql"
#import "@/queries/component-blocks/entourage-block.gql"
#import "@/queries/component-blocks/image-carousel-block.gql"
#import "@/queries/component-blocks/recommendation-block.gql"
#import "@/queries/page-templates/page-seo.gql"
#import "@/queries/page-templates/page-injection.gql"

query QUERY_PAGE_BY_SLUG($slug: String!, $isPreview: Boolean!) {
  componentPageCollection(
    where: { pageSlug: $slug }
    limit: 1
    preview: $isPreview
  ) {
    items {
      pageName
      pageSlug
      pageSeo {
        ...PageSeoFragment
      }
      pageContentsCollection {
        items {
          ... on ComponentHeader {
            ...HeaderFragment
          }
          ... on ComponentFooter {
            ...FooterFragment
          }
          ... on ComponentMainHero {
            ...MainHeroFragment
          }
          ... on ComponentSimpleBlock {
            ...SimpleBlockFragment
          }
          ... on ComponentAttireBlock {
            ...AttireBlockFragment
          }
          ... on ComponentTimelineBlock {
            ...TimelineBlockFragment
          }
          ... on ComponentEntourageBlock {
            ...EntourageBlockFragment
          }
          ... on ComponentImageCarouselBlock {
            ...ImageCarouselBlockFragment
          }
          ... on ComponentRecommendationBlock {
            ...RecommendationBlockFragment
          }
          ... on ComponentPageInjection {
            ...PageInjectionFragment
          }
        }
      }
    }
  }
}
