#import "@/queries/component-blocks/attire-card.gql"
#import "@/queries/component-blocks/image-carousel.gql"

fragment AttireBlockFragment on ComponentAttireBlock {
  sys {
    id
  }
  __typename
  attireBlockTitle
  attireBlockSubtitle
  attireBlockBody
  attireBlockCardsCollection(limit: 3) {
    items {
      ... on ComponentAttireCard {
        ...AttireCardFragment
      }
      ... on ComponentImageCarousel {
        ...ImageCarouselFragment
      }
    }
  }
  attireBlockClassName
}
