#import "@/queries/building-blocks/basic-media.gql"
#import "@/queries/building-blocks/basic-link.gql"

fragment FooterFragment on ComponentFooter {
  sys {
    id
  }
  __typename
  footerText
  footerBackground {
    ...BasicMediaFragment
  }
  footerLogo {
    ...BasicMediaFragment
  }
  footerVariant
  footerLinksCollection(limit: 5) {
    items {
      ...BasicLinkFragment
    }
  }
}
