#import "@/queries/building-blocks/basic-media.gql"

fragment FooterFragment on ComponentFooter {
  sys {
    id
  }
  __typename
  footerText
  footerBackground {
    ...BasicMediaFragment
  }
  footerLogo {
    ...BasicMediaFragment
  }
}
