#import "@/queries/building-blocks/basic-media.gql"
#import "@/queries/building-blocks/basic-link.gql"

fragment HeaderFragment on ComponentHeader {
  sys {
    id
  }
  __typename
  headerName
  headerLogo {
    ...BasicMediaFragment
  }
  headerLinksCollection(limit: 6) {
    items {
      ...BasicLinkFragment
    }
  }
}
