#import "@/queries/building-blocks/basic-media.gql"

fragment HeroFragment on ComponentHero {
  sys {
    id
  }
  __typename
  heroName
  heroTitle
  heroSubtitle
  heroCaption
  heroBody
  heroImage {
    ...BasicMediaFragment
  }
}
