#import "@/queries/building-blocks/basic-media.gql"
#import "@/queries/component-blocks/attire-card.gql"

fragment ImageCarouselFragment on ComponentImageCarousel {
  sys {
    id
  }
  __typename
  imageCarouselTitle
  imageCarouselCover {
    ...AttireCardFragment
  }
  imageCarouselItemsCollection(limit: 10) {
    items {
      ... on ComponentBasicMedia {
        ...BasicMediaFragment
      }
    }
  }
}
