#import "@/queries/component-blocks/timeline-item.gql"
#import "@/queries/building-blocks/basic-media.gql"

fragment TimelineBlockFragment on ComponentTimelineBlock {
  sys {
    id
  }
  __typename
  timelineBlockItemsCollection(limit: 4) {
    items {
      ...TimelineItemFragment
    }
  }
  timelineBlockBackgroundImage {
    ...BasicMediaFragment
  }
}
