import "@/app/assets/styles/globals.css";
import {
  ApercuMono,
  ApercuPro,
  KuenstlerScript,
  ProximaSera
} from "@/app/fonts";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ApercuPro.variable} ${ApercuMono.variable} ${ProximaSera.variable} ${KuenstlerScript.variable} antialiased`}
      >
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
