fragment BasicMediaFragment on ComponentBasicMedia {
  sys {
    id
  }
  __typename
  basicMediaName
  basicMediaImage {
    url
    description
    height
    width
  }
  basicMediaAltText
  basicMediaHeight
  basicMediaWidth
  basicMediaFill
  basicMediaEager
  basicMediaPriority
  basicMediaLinkUrl
  basicMediaLinkIsExternal
}
